{% set name = "apache-airflow-providers-apache-hive" %}
{% set version = "6.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-apache-hive-{{ version }}.tar.gz
  sha256: 057a708efdd32f029612038ff0470fed6ea48b85b0e78047db7511f8522c6347

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools >=67.2.0,<68.0.0
    - pip
  run:
    - python
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow >=2.4.0
    - hmsclient >=0.1.0
    - pandas >=0.17.1
    - pyhive >=0.6.0

    # pyhive[hive]
    - sasl >=0.2.1
    - thrift >=0.10.0
    - thrift_sasl >=0.1.0

    - sasl >=0.3.1  # [py>=39]
    - thrift >=0.9.2

test:
  imports:
    - airflow.providers.apache.hive
    - airflow.providers.apache.hive.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-apache-hive package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-hive/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
