{% set name = "apache-airflow-providers-apache-hive" %}
{% set version = "8.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_hive-{{ version }}.tar.gz
  sha256: cb8221f898d4ac0984fa1a38eb70f85c71e40de9ef3fac7ceb7667639b534939

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow >=2.7.0
    - hmsclient >=0.1.0
    - pandas >=1.2.5,<2.2
    - pyhive >=0.7.0

    # pyhive[hive]
    - sasl >=0.2.1
    - thrift >=0.10.0
    - thrift_sasl >=0.1.0

    - thrift >=0.9.2

test:
  imports:
    - airflow.providers.apache.hive
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-hive for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apache/hive/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-hive/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
