{% set name = "apache-airflow-providers-apache-hive" %}
{% set version = "9.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_hive-{{ version }}.tar.gz
  sha256: fcb4f883d1cd0ecf8fc754a6ca76daa5736b7e69187c9cfbc61cb70e70814c3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.11.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.9.0
    - apache-airflow-providers-common-sql >=1.20.0
    - hmsclient >=0.1.0
    - pandas >=2.1.2,<2.2
    - pyhive >=0.7.0

    # pyhive[hive]
    - sasl >=0.2.1
    - thrift >=0.11.0
    - thrift_sasl >=0.1.0

    - thrift >=0.11.0
    - jmespath >=0.7.0

test:
  imports:
    - airflow.providers.apache.hive
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-hive for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/apache/hive/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-hive/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
