{% set name = "apache-airflow-providers-apache-hive" %}
{% set version = "8.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_hive-{{ version }}.tar.gz
  sha256: 94fc522bdcdd4d11e2e883c70a0d5ba4140b1c47d5fc3743659aecb30e92163d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow >=2.8.0
    - hmsclient >=0.1.0
    - jmespath >=0.7.0
    - pandas >=2.1.2,<2.2
    - pyhive >=0.7.0

    # pyhive[hive]
    - sasl >=0.2.1
    - thrift >=0.11.0
    - thrift_sasl >=0.1.0

    - thrift >=0.9.2

test:
  imports:
    - airflow.providers.apache.hive
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-hive for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apache/hive/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-hive/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
