{% set name = "apache-airflow-providers-apache-hive" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-apache-hive-{{ version }}.tar.gz
  sha256: df0734218b9d64d0d8f6f32f8fc6e7d2ebbf155c8d810ede1ef5d6700dd0e2ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - setuptools >=67.2.0,<68.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - apache-airflow-providers-common-sql >=1.3.1
    - apache-airflow >=2.5.0
    - hmsclient >=0.1.0
    - pandas >=0.17.1
    - pyhive >=0.7.0

    # pyhive[hive]
    - sasl >=0.2.1
    - thrift >=0.10.0
    - thrift_sasl >=0.1.0

    - thrift >=0.9.2

test:
  imports:
    - airflow.providers.apache.hive
    - airflow.providers.apache.hive.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-apache-hive package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-hive/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
